# The documentation for the contents of this file can be found at:
# https://docs.gitlab.com/ce/ci/yaml/README.html

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
# The recipe for this docker image can be found at:
# https://github.com/rust-lang/docker-rust/blob/3dea3da5cb709648d53b2a50ba89aef9c89bdd96/1.46.0/buster/Dockerfile
image: "rust:1.46.0"

stages:
  - build
  - test

build:cargo:
  stage: build
  artifacts:
    paths:
      - target/
  script:
  - rustup target add wasm32-unknown-unknown
  - rustc --version && cargo --version
  - cargo build --lib --tests --verbose
  - cargo build --lib --tests --verbose --release
  - cargo build --lib --tests --verbose --target=wasm32-unknown-unknown
  - cargo build --lib --tests --verbose --release --target=wasm32-unknown-unknown

test:cargo:
  stage: test
  dependencies:
  - build:cargo
  script:
  - rustup target add wasm32-unknown-unknown
    # firefox-geckodriver is only available on Ubuntu. So make its
    # repository known.
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ focal main universe' >> /etc/apt/sources.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C
  - apt-get update
    # Node.js is the default test backend and we don't change it for the
    # unit tests. All other tests run in a headless browser, we use
    # Firefox.
  - apt-get install --assume-yes nodejs firefox-geckodriver
  - make test-runner
  - make test

lint:clippy:
  stage: test
  dependencies:
    - build:cargo
  script:
  - rustup component add clippy
  # TODO: Once we removed deprecated features we should remove the -A
  #       part.
  - cargo clippy --all-targets --all-features -- -A deprecated -D warnings
